#!/bin/bash
# /etc/init.d/uavboot

### BEGIN INIT INFO
# Provides:          uavboot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 2 5 4
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

USER=odroid
HOME=/home/odroid

export USER HOME

case "$1" in
 start)
  echo "Starting UAV controller"
  su - $USER -c "/home/odroid/Desktop/yifan/src/uav_control/src/boot/boot.sh"
  ;;

 stop)
  echo "Stopping UAV controller"
  ;;

 *)
  echo "Usage: /etc/init.d/vncboot {start|stop}"
  exit 1
  ;;
esac

exit 0
